/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

group = "com.heroslender"
version = "4.6.2"
description = "HeroSpawners"

repositories {
    mavenLocal()
    mavenCentral()

    maven("https://nexus.heroslender.com/repository/maven-public/")
    maven("https://repo.maven.apache.org/maven2/")
    maven("https://jitpack.io")
    maven("https://repo.codemc.org/repository/maven-public/")
    maven("https://repo.dustplanet.de/artifactory/libs-release-local")
    maven("https://hub.spigotmc.org/nexus/content/groups/public/")
}

dependencies {
    implementation("org.apache.commons:commons-lang3:3.10")
    implementation("com.zaxxer:HikariCP:3.4.5")
    implementation("org.apache.logging.log4j:log4j-core:2.17.1")
    compileOnly("org.xerial:sqlite-jdbc:3.28.0")
    compileOnly("org.projectlombok:lombok:1.18.12")
    compileOnly("org.jetbrains:annotations:19.0.0")
    compileOnly("com.github.decentsoftware-eu:decentholograms:2.3.1")
    compileOnly("uk.antiperson.stackmob:StackMob:5.5.4")
    compileOnly("com.gmail.filoghost.holographicdisplays:holographicdisplays-api:2.4.0")
    compileOnly("de.dustplanet:silkspawners:7.4.0") {
        exclude(group = "org.spigotmc")
        exclude(group = "com.sk89q")
        exclude(group = "com.massivecraft.massivecore")
        exclude(group = "com.massivecraft.factions")
        exclude(group = "net.gravitydevelopment.updater")
    }

    compileOnly(fileTree("Libs"))

    compileOnly("org.spigotmc:spigot:1.8.8-R0.1-SNAPSHOT")
}

java {
    withJavadocJar()
    withSourcesJar()

    targetCompatibility = JavaVersion.VERSION_1_8
    sourceCompatibility = JavaVersion.VERSION_1_8
}

tasks {
    compileJava {
        options.encoding = Charsets.UTF_8.name()
    }

    javadoc {
        options.encoding = Charsets.UTF_8.name()
    }

    processResources {
        filteringCharset = Charsets.UTF_8.name()
    }
}
